### ISSUE TITLE
Timeouts on slow sever response

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-client#473]
When using Fractal client at FMI, the server is sometimes slower to respond to requests. It's typically the first request made as a given user (within a given time period), e.g. creating the project or collecting tasks. Subsequent requests seem to go faster, so maybe it's authentication related.

I sometimes run into this error when running the `setup_multi_user.sh` script (when it tries to start the task collection):
```
Traceback (most recent call last):
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1265, in receive
    await self._protocol.read_event.wait()
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/asyncio/locks.py", line 226, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 36, in read
    return b""
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpcore/_async/http11.py", line 112, in handle_async_request
    raise exc
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpcore/_async/http11.py", line 91, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpcore/_async/http11.py", line 155, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpcore/_async/http11.py", line 191, in _receive_event
    data = await self._network_stream.read(
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 36, in read
    return b""
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/fractal-client-1.2.0a0/bin/fractal", line 8, in <module>
    sys.exit(run())
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/fractal/__main__.py", line 7, in run
    asyncio.run(main())
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/fractal/client.py", line 114, in main
    interface = await handle()
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/fractal/client.py", line 104, in handle
    interface = await handler(client, **kwargs)
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/fractal/cmd/__init__.py", line 124, in task
    iface = await task_collect_pip(client, batch=batch, **kwargs)
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/fractal/cmd/_task.py", line 42, in task_collect_pip
    res = await client.post(
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/fractal/authclient.py", line 112, in post
    return await self.client.post(
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/path/to/fractal-client-1.2.0a0/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout
```

Task collection actually does start and complete successfully though.

**Comment by tcompa** [comment]
On the one hand, we can modify/remove the timeout from the client (https://www.python-httpx.org/advanced/#timeout-configuration). On the other hand, we could debug a bit further to see what is taking so long.

**Comment by jluethi** [comment]
Would be nice to debug what is causing the delays, but let's get back to this later, because there are higher priority issues to tackle atm. => maintenance for some point.

I'll follow up on this issue if I run into it again and we can increase the timeout if it starts interfering with workflows.

**Comment by jluethi** [comment]
Not observed anymore, let's reopen if it comes up again
